site_name: JUMA 文档中心
site_url: http://www.juma.io/doc/zh/
repo_url: https://github.com/JUMA-IO/JUMA_Docs
docs_dir: sources
theme_dir: theme/updocs
#theme: bootstrap
copyright: Copyright &copy; 2015, JUMA

pages:

- '文档中心': 
    - '文档首页': 'basics/index.md'
    - 'SDK概述': 'basics/intro.md'
    - '技术支持': 'basics/support.md'
    - '关于我们': 'basics/aboutus.md'
    - '法律条款': 'basics/legal.md'
    - '技术话题: BLE入门教程': 'basics/ble_first.md'
    - '技术话题: IoT嵌入式编程': 'basics/embedded_iot.md'
- '嵌入式SDK':
    - '使用说明': 'embedded_api/guide.md'
    - '系统和任务': 'embedded_api/task.md'
    - 'BLE从设备': 'embedded_api/ble.md'
    - 'BLE主设备': 'embedded_api/ble_master.md'
    - 'JSensor': 'embedded_api/jsensor.md'
    - 'GPIO': 'embedded_api/gpio.md'
    - 'SPI总线': 'embedded_api/spi.md'
    - '串口总线': 'embedded_api/serial.md'
    - '定时器': 'embedded_api/timer.md'
    - '看门狗': 'embedded_api/wdog.md'
    - '非易失性存储': 'embedded_api/storage.md'
    - 'USB': 'embedded_api/usb.md'
    - '调光灯': 'embedded_api/light.md'
    - '蜂蜜器': 'embedded_api/buzz.md'
    - '红外发射': 'embedded_api/infrared.md'
    - '模数转换': 'embedded_api/adc.md'
    - '图形库': 'embedded_api/gfx.md'
- 'Android SDK':
    - '使用说明': 'android_api/guide.md'
    - '扫描类': 'android_api/scan.md'
    - '设备类': 'android_api/device.md'
- 'iOS SDK':
    - '使用说明': 'ios_api/guide.md'
    - '管理类': 'ios_api/manager.md'
    - '设备类': 'ios_api/device.md'
- 'nRF51平台':
    - 'test': 'nrf51_platform/test.md'
- 'STM32平台':
    - 'test': 'stm32_platform/test.md'


# Add permalink for sharing
markdown_extensions:
    - toc:
        permalink: True
