site_name: JUMA 文档中心
site_url: http://www.juma.io/doc/zh/
repo_url: https://github.com/JUMA-IO/JUMA_Docs
docs_dir: sources
theme_dir: theme/updocs
#theme: bootstrap
copyright: Copyright &copy; 2015, JUMA

pages:

- '文档首页': 'index.md'
- '嵌入式SDK':
    - 'BLE从设备': 'embedded_api/ble.md'
    - 'BLE主设备': 'embedded_api/ble_master.md'
    - 'JSensor传感器': 'embedded_api/jsensor.md'
    - '定时器': 'embedded_api/timer.md'
    - '任务调度': 'embedded_api/time_task.md'
- 'Android SDK':
    - 'test': 'android_api/test.md'
- 'iOS SDK':
    - 'test': 'ios_api/test.md'
- 'nRF51平台':
    - 'test': 'nrf51_platform/test.md'
- 'STM32平台':
    - 'test': 'stm32_platform/test.md'


# Add permalink for sharing
markdown_extensions:
    - toc:
        permalink: True
